### ISSUE TITLE
release: chrome webstore

### ISSUE THREAD

**Issue by Nasfame** [AminoffZ/github-repo-size#16]
@AminoffZ why haven't u published ur app to webstore

**Comment by AminoffZ** [comment]
It's right [here](https://chrome.google.com/webstore/detail/github-repo-size/jpdmfnflpdgefbfkafcikmhipofhanfl)!

![image](https://github.com/AminoffZ/github-repo-size/assets/55880031/fb5050c6-b634-4af0-9d44-eacaf620cb0c)
