### ISSUE TITLE
Port to browser API from chrome API for a wider browser compatibility

### ISSUE THREAD

**Issue by mAmineChniti** [AminoffZ/github-repo-size#25]
**Is your feature request related to a problem? Please describe.**
The "github-repo-size" extension currently relies on the Chrome API, limiting its compatibility to Chrome-based browsers. This poses a problem for users who prefer other browsers and would like to use the extension.

**Describe the solution you'd like**
I propose transitioning the extension from the Chrome API to the more universal browser API. This change would enhance compatibility, allowing users to enjoy the "github-repo-size" extension across a broader range of browsers.

**Describe alternatives you've considered**
Maintaining two versions of the extension, one for Chrome and another for browsers that support the browser API natively.

**Additional context**
N/A

**Comment by AminoffZ** [comment]
I was wrong in assuming Manifest V3 was completely supported by Firefox. Although [this](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/) states that _Manifest V3 became generally available in Firefox 109_, service workers are currently disabled, which this extension relies on: https://github.com/mozilla/web-ext/issues/2532.

**Comment by mAmineChniti** [comment]
From what i gathered they're disabled by default on firefox but that could be changed by setting `extensions.backgroundServiceWorker.enabled` to `true` in `about:config`

**Comment by AminoffZ** [comment]
https://github.com/mozilla/web-ext/issues/2532#issuecomment-1992345597

**Comment by mAmineChniti** [comment]
@AminoffZ hey welcome back glad to have you, i've actually finished the task and tested the extension in firefox and it works very well
