### ISSUE TITLE
Plugin not working if current page has git submodule

### ISSUE THREAD

**Issue by publicqi** [AminoffZ/github-repo-size#26]
**Describe the bug**
The plugin is not rendering the size tab nor the size of other files when there's a submodule in page. I did not test if this also exists in sub folders of a repo, but it does not show size in the main page.

**To Reproduce**
1. Goto https://github.com/frida/frida/
2. The size is not showing

**Expected behavior**
I guess it should just ignore the submodule size?

**Screenshots**

**Platform:**

**Additional context**

**Comment by AminoffZ** [comment]
Thanks for pointing this out. This was partly noted in #9 but due to the recent update, it's gotten more critical.

**Comment by AminoffZ** [comment]
Thanks for pointing this out. This was partly noted in #9 but due to the recent update, it's gotten more critical.

**Comment by mAmineChniti** [comment]
Thank you for letting us know, this is a duplicate issue we have already flagged this #9 and will be working on it, if you'd be so kind as to close down this issue, if you're interested in fixing it on your own https://github.com/AminoffZ/github-repo-size/blob/main/CONTRIBUTING.md we're accepting PRs.
