### ISSUE TITLE
Unable to get the default branch of private repo

### ISSUE THREAD

**Issue by XZTDean** [AminoffZ/github-repo-size#30]
**Describe the bug**
If accessing a private repo with the default branch is not "main". The repo size cannot be displayed. But with the branch specified in the URL, the size can be correctly displayed.

I found if there is no branch in the URL, it still sends requests to query the size of the "main" branch. And the repo info API returns 404.

**To Reproduce**

1. Open a private repo with the default branch is not "main"
2. The extension cannot display the size of repo
3. Add the default branch in URL
4. The extension can display the size of repo

**Expected behavior**
The size of repo be correctly displayed.

**Platform:**

- OS: Windows
- Browser: Chrome
- Version: 120

**Additional context**
I guess the problem may be related to the GitHub token is not used when sending requests to repo info API. It makes the private repo not accessible.

**Comment by mAmineChniti** [comment]
Thank you for your report, github-repo-size struggles a bit with private repos even tho we have the api auth system in place, i'll be working on this issue after i finish porting to all browsers, if you're interested in this you can solve this issue and PR [CONTRIBUTING.md](https://github.com/AminoffZ/github-repo-size/blob/main/CONTRIBUTING.md)
