### ISSUE TITLE
Placement of the Total Size Element

### ISSUE THREAD

**Issue by AminoffZ** [AminoffZ/github-repo-size#8]
Currently the total size element is shown at the very top at the page. This was intentional as then it is always visible when navigating around a repo's page. However, we should consider also displaying it at more intuitive places on the repo's home page. As a side-note the element is currently by mistake **inside** the settings li element. This creates an unexpected look when selecting the settings tab.
![image](https://github.com/AminoffZ/github-repo-size/assets/55880031/58b294fe-b42d-4ab9-acc8-93cfe761e01e).

Files to look at:
- src/scripts/internal/selectors.ts 
- src/scripts/internal/dom-manipulator.ts
- src/scripts/internal/element-factory.ts

**Comment by mAmineChniti** [comment]
so far i've made some progress on this i managed to separate the elements, but for some reason the underline effect is still there, its a part of `UnderlineNav-item` but i couldn't find what exactly does or undoes it
